# Each new term in the Fibonacci sequence is generated by 
# adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
#
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence
# which do not exceed four million.

a = 1  # the number preceding the first even no in sequence
b = 2  # the first even no
 
result = 0

while True:
    if b > 4000000:
        break
    
    result += b
    temp_a = 2*b + a
    b = 3*b + 2*a
    a = temp_a

print result
